/**
 * DTCG (Design Tokens Community Group) 2025.10 形式のトークンを読み込み、alias を解決し、
 * テーマ別の CSS custom properties (`--ad-*`) を生成する純ロジック。
 *
 * - 形式: `{ "$value": "...", "$type": "color" }`。alias は `"{a.b.c}"`。
 * - 階層: primitive / semantic / component を base にマージ、theme-* を上書き層とする。
 * - CSS では alias を `var(--ad-target)` として emit するため、theme が primitive を上書きすると
 *   それを参照する semantic/component が自動で追従する（単一ソース）。
 * - 出所安定版: www.designtokens.org/tr/2025.10/format/。
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { z } from "zod";

/** DTCG leaf: $value 必須、$type/$description 任意。 */
const leafSchema = z.object({
  $value: z.union([z.string(), z.number()]),
  $type: z.string().optional(),
  $description: z.string().optional(),
});

/** ネストした DTCG group（leaf でない node は子 group）。 */
type DtcgNode = { [key: string]: DtcgNode } | { $value: string | number; $type?: string };

export interface FlatToken {
  /** ドット区切りパス（例 `fg.primary` / `color.neutral.0`）。 */
  readonly path: string;
  readonly type: string | undefined;
  /** リテラル（`#rrggbb` / `8px` 等）または alias `{a.b.c}`。 */
  readonly value: string;
}

export const THEME_NAMES = ["light", "dark", "hc"] as const;
export type ThemeName = (typeof THEME_NAMES)[number];

export interface ThemeLayer {
  readonly name: Exclude<ThemeName, "light">;
  /** 明示テーマ選択用セレクタ。 */
  readonly selector: string;
  /** 明示テーマ未指定時に system 設定で自動適用する media query。 */
  readonly media: string;
  readonly tokens: readonly FlatToken[];
}

export interface TokenSources {
  /** primitive + semantic + component をこの順でマージした base（light テーマ）。 */
  readonly base: readonly FlatToken[];
  readonly themes: readonly ThemeLayer[];
}

const ALIAS_RE = /^\{([^}]+)\}$/;

export function isAlias(value: string): boolean {
  return ALIAS_RE.test(value);
}

export function aliasTarget(value: string): string {
  const m = ALIAS_RE.exec(value);
  if (!m) throw new Error(`not an alias: ${value}`);
  return m[1]!;
}

/** `fg.primary` → `--ad-fg-primary`。 */
export function pathToVar(path: string): string {
  return `--ad-${path.replace(/\./g, "-")}`;
}

/** ネスト DTCG オブジェクトを FlatToken[] へ。leaf = `$value` を持つ node。 */
export function flatten(node: DtcgNode, prefix = ""): FlatToken[] {
  const out: FlatToken[] = [];
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue; // $description などグループメタは無視
    const path = prefix ? `${prefix}.${key}` : key;
    if (child && typeof child === "object" && "$value" in child) {
      const leaf = leafSchema.parse(child);
      out.push({ path, type: leaf.$type, value: String(leaf.$value) });
    } else if (child && typeof child === "object") {
      out.push(...flatten(child as DtcgNode, path));
    }
  }
  return out;
}

/**
 * alias をリテラルまで解決する（contrast 検査用）。base に theme override を重ねた map に対して
 * `path` を解決。循環は例外。dangling 参照（未定義 alias）は例外＝INV-TOKEN-RESOLVE で赤化。
 */
export function resolveLiteral(
  path: string,
  map: ReadonlyMap<string, string>,
  seen: ReadonlySet<string> = new Set(),
): string {
  const value = map.get(path);
  if (value === undefined) throw new Error(`dangling token reference: ${path}`);
  if (!isAlias(value)) return value;
  const target = aliasTarget(value);
  if (seen.has(target)) throw new Error(`alias cycle at: ${target}`);
  return resolveLiteral(target, map, new Set(seen).add(path));
}

/** base + theme override をマージした path→value マップ（未解決 alias のまま）。 */
export function mergedMap(
  base: readonly FlatToken[],
  override: readonly FlatToken[] = [],
): Map<string, string> {
  const m = new Map<string, string>();
  for (const t of base) m.set(t.path, t.value);
  for (const t of override) m.set(t.path, t.value);
  return m;
}

/** 1 トークンの CSS 宣言値（alias は var() 参照、リテラルはそのまま）。 */
function cssValue(value: string): string {
  return isAlias(value) ? `var(${pathToVar(aliasTarget(value))})` : value;
}

function emitBlock(selector: string, tokens: readonly FlatToken[], indent = "  "): string {
  const lines = tokens.map((t) => `${indent}${pathToVar(t.path)}: ${cssValue(t.value)};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

/**
 * テーマ別 CSS を生成。
 * - `:root` に base（light）。
 * - 各 theme を `[data-theme="x"]`（明示）と `@media`（system 追従・明示テーマ無し時）に emit。
 * - motion.duration.* は `@media (prefers-reduced-motion: reduce)` で 0ms に落とす（Reduced Motion）。
 */
export function generateCss(sources: TokenSources): string {
  const parts: string[] = [
    "/* GENERATED by @actradeck/design-tokens (build-tokens.mjs). DO NOT EDIT. */",
    emitBlock(":root", sources.base),
  ];

  for (const theme of sources.themes) {
    parts.push(emitBlock(theme.selector, theme.tokens));
    // 明示テーマが選ばれていないときだけ system 設定で自動適用する。
    parts.push(
      `@media ${theme.media} {\n${emitBlock(":root:not([data-theme])", theme.tokens, "    ")}\n}`,
    );
  }

  // Reduced Motion: motion duration トークンを 0 に。明示テーマに依存しない横断適用。
  const motionZero = sources.base
    .filter((t) => t.path.startsWith("motion.duration."))
    .map((t) => `    ${pathToVar(t.path)}: 0ms;`);
  if (motionZero.length > 0) {
    parts.push(
      `@media (prefers-reduced-motion: reduce) {\n  :root {\n${motionZero.join("\n")}\n  }\n}`,
    );
  }

  return parts.join("\n\n") + "\n";
}

/** トークンディレクトリから DTCG ファイル群を読み、TokenSources を構築。 */
export function loadSources(dir: string): TokenSources {
  const read = (f: string): DtcgNode => JSON.parse(readFileSync(`${dir}/${f}`, "utf8")) as DtcgNode;

  const base: FlatToken[] = [
    ...flatten(read("primitive.tokens.json")),
    ...flatten(read("semantic.tokens.json")),
    ...flatten(read("component.tokens.json")),
  ];
  const themes: ThemeLayer[] = [
    {
      name: "dark",
      selector: '[data-theme="dark"]',
      media: "(prefers-color-scheme: dark)",
      tokens: flatten(read("theme-dark.tokens.json")),
    },
    {
      name: "hc",
      selector: '[data-theme="hc"]',
      media: "(prefers-contrast: more)",
      tokens: flatten(read("theme-hc.tokens.json")),
    },
  ];
  return { base, themes };
}

/** テスト/ビルド双方が同じ src/tokens を指すための既定ディレクトリ。 */
export function defaultTokensDir(): string {
  return fileURLToPath(new URL("./tokens", import.meta.url));
}
